name: Auto_Sync OpenWRT Releases

on:
  schedule:
    - cron: '30 23 */1 * *'
  workflow_dispatch:

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    outputs:
      release_exists: ${{ steps.check_release.outputs.release_exists }}
      release_tag: ${{ steps.get_release.outputs.release_tag }}
      can_proceed: ${{ steps.check_metadata.outputs.can_proceed }}
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get the latest release from OpenWRT
        id: get_release
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest | jq -r '.tag_name')
          echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: Check if release exists in your repo
        id: check_release
        run: |
          RELEASE_URL="https://api.github.com/repos/samara1531/amneziawg-openwrt/releases/tags/${{ steps.get_release.outputs.release_tag }}"
          MAX_RETRIES=3
          for ((i=1; i<=MAX_RETRIES; i++)); do
            RESPONSE=$(curl -s -w "%{http_code}" -o response.json $RELEASE_URL)
            if [ "$RESPONSE" -eq 200 ]; then
              echo "release_exists=true" >> $GITHUB_OUTPUT
              break
            elif [ "$RESPONSE" -eq 404 ]; then
              echo "release_exists=false" >> $GITHUB_OUTPUT
              break
            else
              echo "Retry $i/$MAX_RETRIES - Error: $RESPONSE"
              sleep 5
            fi
          done
          cat response.json  # Log for diagnostics

      - name: Check saved release tag and timestamp
        id: check_metadata
        run: |
          echo "Comparing the saved release tag and its timestamp."
          if [ -f saved_release_metadata.txt ]; then
            IFS=',' read SAVED_TAG SAVED_DATE < saved_release_metadata.txt
            LATEST_TAG="${{ steps.get_release.outputs.release_tag }}"
            LATEST_DATE="${{ steps.get_release.outputs.release_date }}"
            echo "Saved Tag: $SAVED_TAG"
            echo "Latest Tag: $LATEST_TAG"
            echo "Saved Date: $SAVED_DATE"
            echo "Latest Date: $LATEST_DATE"
            if [ "$SAVED_TAG" == "$LATEST_TAG" ]; then
              SAVED_EPOCH=$(date -d "$SAVED_DATE" +%s)
              CURRENT_TIME=$(date +%s)
              AGE=$(( (CURRENT_TIME - SAVED_EPOCH) / 3600 ))
              if (( AGE <= 75 )); then
                echo "Tag matches and is not older than 75 hours. Proceeding."
                echo "can_proceed=true" >> $GITHUB_OUTPUT
              else
                echo "Tag matches but is older than 75 hours. Stopping."
                echo "can_proceed=false" >> $GITHUB_OUTPUT
              fi
            else
              echo "Tags do not match. Not proceeding."
              echo "can_proceed=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "The saved_release_metadata.txt file does not exist. Cannot proceed."
            echo "can_proceed=false" >> $GITHUB_OUTPUT

      - name: Save RELEASE_TAG and current DATE to file only if changed
        run: |
          git checkout master
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [ -f saved_release_metadata.txt ]; then
            IFS=',' read SAVED_TAG SAVED_DATE < saved_release_metadata.txt
            echo "Saved Tag: $SAVED_TAG"
          else
            SAVED_TAG=""
            echo "No saved release metadata. Assuming it is empty."
          fi

          CURRENT_TAG="${{ steps.get_release.outputs.release_tag }}"

          if [ "$SAVED_TAG" != "$CURRENT_TAG" ]; then
            echo "Tag has changed. Updating saved_release_metadata.txt."
            CURRENT_DATE=$(date "+%Y-%m-%d %H:%M:%S")
            echo "$CURRENT_TAG,$CURRENT_DATE" > saved_release_metadata.txt
            git add saved_release_metadata.txt
            git commit --allow-empty -m "Update release metadata with tag and current date"
            git push origin master
          else
            echo "Tag has not changed. saved_release_metadata.txt will not be updated."

      - name: Create release in your repo
        if: steps.check_release.outputs.release_exists == 'false' && steps.check_metadata.outputs.can_proceed == 'true'
        run: |
          curl -X POST https://api.github.com/repos/samara1531/amneziawg-openwrt/releases \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          {
            "tag_name": "${{ steps.get_release.outputs.release_tag }}",
            "name": "OpenWrt ${{ steps.get_release.outputs.release_tag }}",
            "body": "A M N E Z I A - W I R E G U A R D"
          }
          EOF

  run-build:
    needs: sync-releases
    if: needs.sync-releases.outputs.can_proceed == 'true'
    uses: samara1531/amneziawg-openwrt/.github/workflows/auto_build.yml@master
    with:
      tag_name: ${{ needs.sync-releases.outputs.release_tag }}
