name: create release

#on:
#  push:
#    tags:
#      - "v*.*.*"

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        type: string
        required: true
        default: "23.05.3"
      openwrt_arch:
        description: "OpenWrt arch"
        type: string
        required: true
        default: "mips_24kc"
      openwrt_target:
        description: "OpenWrt target"
        type: string
        required: true
        default: "ath79"
      openwrt_subtarget:
        description: "OpenWrt subtarget"
        type: string
        required: true
        default: "generic"
      openwrt_vermagic:
        description: "OpenWrt vermagic"
        type: string
        required: true
        default: "auto"

jobs:
  build:
    name: "v${{ matrix.build_env.tag }} - ${{ matrix.build_env.pkgarch }} :: ${{ matrix.build_env.target }}/${{ matrix.build_env.subtarget }} amneziawg release"
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_env:
          - tag: ${{ inputs.openwrt_version || vars.DEFAULT_OPENWRT_VERSION }}
            pkgarch: ${{ inputs.openwrt_arch || vars.DEFAULT_OPENWRT_ARCH }}
            target: ${{ inputs.openwrt_target || vars.DEFAULT_OPENWRT_TARGET }}
            subtarget: ${{ inputs.openwrt_subtarget || vars.DEFAULT_OPENWRT_SUBTARGET }}
            vermagic: ${{ inputs.openwrt_vermagic || vars.DEFAULT_OPENWRT_VERMAGIC }}

    env:
      OPENWRT_RELEASE: ${{ matrix.build_env.tag }}
      OPENWRT_ARCH: ${{ matrix.build_env.pkgarch }}
      OPENWRT_TARGET: ${{ matrix.build_env.target }}
      OPENWRT_SUBTARGET: ${{ matrix.build_env.subtarget }}
      OPENWRT_VERMAGIC: ${{ matrix.build_env.vermagic }}

    steps:
      - name: checkout amneziawg-openwrt
        uses: actions/checkout@v4
        with:
          path: amneziawg-openwrt
          fetch-depth: 0

      - name: check amneziawg-openwrt release readiness
        id: check-amneziawg-release
        run: |
          set -x
          cd amneziawg-openwrt
          make show-env
          make check-release

      - name: checkout openwrt
        uses: actions/checkout@v4
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: v${{ matrix.build_env.tag }}
          fetch-depth: 0

      - name: checkout usign
        uses: actions/checkout@v4
        with:
          path: usign
          repository: openwrt/usign
          fetch-depth: 0

      - name: build usign
        id: build-usign
        run: |
          set -x
          cd usign
          mkdir build
          cd build
          cmake ..
          make -j
          echo "$(pwd)" >> $GITHUB_PATH

      - name: restore cached tools and kernel
        id: cache-tools-kernel-restore
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          key: ${{ runner.os }}-openwrt-cache-toolchain-kernel-${{ matrix.build_env.tag }}-${{ matrix.build_env.pkgarch }}-${{ matrix.build_env.target }}-${{ matrix.build_env.subtarget }}
          restore-keys: |
            ${{ runner.os }}-openwrt-cache-tools-kernel-${{ matrix.build_env.pkgarch }}-
          path: |
            openwrt/.config
            openwrt/.config.old
            openwrt/feeds.conf
            openwrt/bin/**
            openwrt/build_dir/**
            openwrt/dl/**
            openwrt/feeds/**
            openwrt/package/**
            openwrt/staging_dir/**
            openwrt/tmp/**

      - name: build amneziawg
        id: build-amneziawg
        run: |
          set -x
          cd amneziawg-openwrt
          make show-env
          time -p make build-amneziawg
          cat << EOF >release.sec
          ${{ secrets.RELEASE_FEED_SEC_KEY }}
          EOF
          cat << EOF >release.pub
          ${{ secrets.RELEASE_FEED_PUB_KEY }}
          EOF
          make prepare-artifacts
          FEED_SEC_KEY=$(pwd)/release.sec FEED_PUB_KEY=$(pwd)/release.pub make prepare-release
          cp release.pub ../awgrelease/amneziawg-public.key

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            awgrelease/*.tar.gz
            awgrelease/amneziawg-public.key
