name: Sync OpenWRT Releases

on:
  schedule:
    - cron: '0 0 */3 * *' # Проверка новых релизов раз в три дня
  workflow_dispatch: # Возможность вручную запустить Action

jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Get the latest release from OpenWRT
        id: get_release
        run: |
          curl -s https://api.github.com/repos/openwrt/openwrt/releases/latest > latest_release.json
          RELEASE_TAG=$(jq -r .tag_name latest_release.json)
          RELEASE_NAME=$(jq -r .name latest_release.json)
          echo "::set-output name=release_tag::$RELEASE_TAG"
          echo "::set-output name=release_name::$RELEASE_NAME"
          
      - name: Check if release exists in your repo
        id: check_release
        run: |
          curl -s https://api.github.com/repos/samara1531/awg-openwrt/releases/tags/${{ steps.get_release.outputs.release_tag }} | jq -r .tag_name || echo "Not found"
          
      - name: Create release in your repo
        run: |
          curl -X POST https://api.github.com/repos/samara1531/awg-openwrt/releases \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "tag_name": "'${{ steps.get_release.outputs.release_tag }}'",
              "name": "'${{ steps.get_release.outputs.release_tag }}'",
              "body": "'"${ART}"'\n\nAutomatically created release for OpenWRT '${{ steps.get_release.outputs.release_tag }}'."
                  }'
                  
      - name: run-build   
        uses: samara1531/awg-openwrt/.github/workflows/build-module.yml@master
        with:
         tag_name: ${{ steps.get_release.outputs.release_tag }}
