name: Create Release aarch64_generic
#on: [push]
on:
  push:
    tags:
      - "*.*.*"

jobs:
  run-build:
    runs-on: ubuntu-latest
     - name: run build-module.yml
      uses: samara1531/awg-openwrt/.github/workflows/build-module.yml@master
